import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "رابطه کاربری جدید ",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="bg-[#1E1F23]">
      <body>{children}</body>
    </html>
  );
}
