import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "داشبورد",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#F4F4F4]">
      <body>{children}</body>
    </html>
  );
}
